- key:               ndc-mainnet
  name:              Ndc Mainnet
  client:            ndcd                             # API client name.
  server:            http://user:password@127.0.0.1:13519 # Public Nexbit node endpoint.
  height:            1200                                # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://explorer.ndcwallet.pro/address/#{address}
    transaction:     https://explorer.ndcwallet.pro/tx/#{txid}
  status:            active
